test_that("is_count accepts whole numbers as.integer() can hold, and nothing else", {
  expect_true(is_count(0))
  expect_true(is_count(2L))
  expect_true(is_count(3, min = 1L))
  expect_true(is_count(.Machine$integer.max))

  expect_false(is_count(0, min = 1L))
  expect_false(is_count(-1))
  expect_false(is_count(1.5))
  expect_false(is_count(NA))
  expect_false(is_count(NA_integer_))
  expect_false(is_count(NaN))
  expect_false(is_count(Inf))
  expect_false(is_count(-Inf))
  expect_false(is_count(.Machine$integer.max + 1))
  expect_false(is_count(c(1, 2)))
  expect_false(is_count(numeric(0)))
  expect_false(is_count("2"))
  expect_false(is_count(TRUE))
  expect_false(is_count(NULL))
})
